ezplatform:
  system:
    default:
      field_templates:
        - { template: '@ezdesign/custom_matrix_fieldtype/content_fields.html.twig', priority: 1 }

    admin_group:
      admin_ui_forms:
        content_edit_form_templates:
          - { template: '@ezdesign/custom_matrix_fieldtype/content_edit_form_fields.html.twig', priority: 1 }
