FileContent:
    type: object
    inherits:
        - AbstractDomainContent
    config:
        interfaces:
            - DomainContent
            - Node
        fields:
            name:
                type: String
                resolve: '@=resolver("DomainFieldValue", [value, "name", args])'
                args:
                    language: { type: RepositoryLanguage }
            description:
                type: RichTextFieldValue
                resolve: '@=resolver("DomainFieldValue", [value, "description", args])'
                args:
                    language: { type: RepositoryLanguage }
            file:
                type: BinaryFileFieldValue
                resolve: '@=resolver("DomainFieldValue", [value, "file", args])'
                args:
                    language: { type: RepositoryLanguage }
