UserContent:
    type: object
    inherits:
        - AbstractDomainContent
    config:
        interfaces:
            - DomainContent
            - Node
        fields:
            firstName:
                type: String
                resolve: '@=resolver("DomainFieldValue", [value, "first_name", args])'
                args:
                    language: { type: RepositoryLanguage }
            lastName:
                type: String
                resolve: '@=resolver("DomainFieldValue", [value, "last_name", args])'
                args:
                    language: { type: RepositoryLanguage }
            userAccount:
                type: String
                resolve: '@=resolver("DomainFieldValue", [value, "user_account", args]).id'
            signature:
                type: String
                resolve: '@=resolver("DomainFieldValue", [value, "signature", args])'
                args:
                    language: { type: RepositoryLanguage }
            image:
                type: ImageFieldValue
                resolve: '@=resolver("DomainFieldValue", [value, "image", args])'
                args:
                    language: { type: RepositoryLanguage }
